### PR TITLE
[BUMP] CommunityBot v2

### PR DESCRIPTION
**Pull request by BrianWasTaken**
- Rewritten to TypeScript
- Migrated to [Sapphire](https://npmjs.com/package/@sapphire/framework) Framework
- ...and much more

Still a WIP. Just here for visibility.

### CODE REVIEW

**Comment by BrianWasTaken** [comment]
@Dauntless7 :skull: just need music and game cmds and we'll get rid of the legacy code in main :smiley: :hocho:

**Comment by BrianWasTaken** [comment]
Still haven't done a dev test though so idrk if we'll get the exact same results on commands and all.

**Comment by Dauntless7** [comment]
> Still haven't done a dev test though so idrk if we'll get the exact same results on commands and all.

I'll try running one tomorrow since it's 3am right now, great progress so far though! A few things need to be updated maybe but that won't be much to do (changes from the main branch + test the moderation censors etc, I can work on that)

**Comment by BrianWasTaken** [comment]
> > Still haven't done a dev test though so idrk if we'll get the exact same results on commands and all.
> 
> I'll try running one tomorrow since it's 3am right now, great progress so far though! A few things need to be updated maybe but that won't be much to do (changes from the main branch + test the moderation censors etc, I can work on that)

Lol alright, mb if I interrupted your slumber so have a good sleep

**Comment by BrianWasTaken** [comment]
Gonna make a separate PR for this. Closing...

**Pull request closed without merging**
